seed: 101
data:
  dt: 0.001
  sample: 50000
  dim: 2
  nt: 11
  T: 1
  plot_path: 'result2D'
train:
  sigma_init: 0.2
  gauss_number: 240
  sampling: SDE
  variance_min: 0.3
  variance_max: 0.7
  lmm: LMM_3

NN:
  width: 100
  depth: 5
  lr: 0.01
  gamma: 0.2
  iter: 2000



  